// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Order struct {
	ID         int32
	UserID     int32
	TotalPrice float64
	CreatedAt  pgtype.Timestamp
}

type OrderItem struct {
	ID        int32
	OrderID   int32
	ProductID int32
	Quantity  int32
}

type Product struct {
	ID          int32
	Name        string
	Ingredients string
	Price       float64
	ImgUrl      string
	CreatedAt   pgtype.Timestamp
	UpdatedAt   pgtype.Timestamp
}

type User struct {
	ID    int32
	Phone string
	Name  string
}
