// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"database/sql"
)

type Order struct {
	ID         int64
	UserID     int64
	TotalPrice float64
	CreatedAt  sql.NullTime
}

type OrderItem struct {
	ID        int64
	ProductID int64
	Quantity  int64
}

type Product struct {
	ID        int64
	Name      string
	Price     float64
	CreatedAt sql.NullTime
	UpdatedAt sql.NullTime
}

type ProductItemsOrder struct {
	OrderItemID int64
	OrderID     int64
}

type User struct {
	ID    int64
	Phone string
	Name  string
}
