// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"database/sql"
)

type Order struct {
	ID         int32
	UserID     int32
	TotalPrice string
	CreatedAt  sql.NullTime
}

type OrderItem struct {
	ID        int32
	ProductID int32
	Quantity  int32
}

type Product struct {
	ID        int32
	Name      string
	Price     string
	CreatedAt sql.NullTime
	UpdatedAt sql.NullTime
}

type ProductItemsOrder struct {
	OrderItemID int32
	OrderID     int32
}

type User struct {
	ID    int32
	Phone string
	Name  string
}
