// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: orders.sql

package db

import (
	"context"
)

const createOrder = `-- name: CreateOrder :one
INSERT INTO orders(
    user_id, total_price
) VALUES (
    $1, $2
)
RETURNING id, user_id, total_price, created_at
`

type CreateOrderParams struct {
	UserID     int32
	TotalPrice float64
}

func (q *Queries) CreateOrder(ctx context.Context, arg CreateOrderParams) (Order, error) {
	row := q.db.QueryRow(ctx, createOrder, arg.UserID, arg.TotalPrice)
	var i Order
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.TotalPrice,
		&i.CreatedAt,
	)
	return i, err
}

const getUserOrders = `-- name: GetUserOrders :many
SELECT id, user_id, total_price, created_at FROM orders
WHERE user_id=$1
ORDER BY created_at DESC
`

func (q *Queries) GetUserOrders(ctx context.Context, userID int32) ([]Order, error) {
	rows, err := q.db.Query(ctx, getUserOrders, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Order
	for rows.Next() {
		var i Order
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.TotalPrice,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
