// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: products.sql

package db

import (
	"context"
)

const getProducts = `-- name: GetProducts :many
SELECT id, name, price, created_at, updated_at FROM products
ORDER BY name
LIMIT ? OFFSET ?
`

type GetProductsParams struct {
	Limit  int64
	Offset int64
}

func (q *Queries) GetProducts(ctx context.Context, arg GetProductsParams) ([]Product, error) {
	rows, err := q.db.QueryContext(ctx, getProducts, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Product
	for rows.Next() {
		var i Product
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Price,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const productsCount = `-- name: ProductsCount :one
SELECT COUNT(id)
FROM products
`

func (q *Queries) ProductsCount(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, productsCount)
	var count int64
	err := row.Scan(&count)
	return count, err
}
