// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: products.sql

package db

import (
	"context"
)

const getProductById = `-- name: GetProductById :one
SELECT id, name, ingredients, price, img_url, created_at, updated_at FROM products
WHERE id=$1
`

func (q *Queries) GetProductById(ctx context.Context, id int32) (Product, error) {
	row := q.db.QueryRowContext(ctx, getProductById, id)
	var i Product
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Ingredients,
		&i.Price,
		&i.ImgUrl,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getProducts = `-- name: GetProducts :many
SELECT id, name, ingredients, price, img_url, created_at, updated_at FROM products
ORDER BY name
LIMIT $1 OFFSET $2
`

type GetProductsParams struct {
	Limit  int32
	Offset int32
}

func (q *Queries) GetProducts(ctx context.Context, arg GetProductsParams) ([]Product, error) {
	rows, err := q.db.QueryContext(ctx, getProducts, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Product
	for rows.Next() {
		var i Product
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Ingredients,
			&i.Price,
			&i.ImgUrl,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const productsCount = `-- name: ProductsCount :one
SELECT COUNT(id)
FROM products
`

func (q *Queries) ProductsCount(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, productsCount)
	var count int64
	err := row.Scan(&count)
	return count, err
}
