// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: users.sql

package db

import (
	"context"
)

const createUser = `-- name: CreateUser :one
INSERT INTO users (
    name, phone
) VALUES (
    $1, $2
) RETURNING id, phone, name
`

type CreateUserParams struct {
	Name  string
	Phone string
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRow(ctx, createUser, arg.Name, arg.Phone)
	var i User
	err := row.Scan(&i.ID, &i.Phone, &i.Name)
	return i, err
}

const getUserByPhone = `-- name: GetUserByPhone :one
SELECT id, phone, name
FROM users
WHERE phone=$1
`

func (q *Queries) GetUserByPhone(ctx context.Context, phone string) (User, error) {
	row := q.db.QueryRow(ctx, getUserByPhone, phone)
	var i User
	err := row.Scan(&i.ID, &i.Phone, &i.Name)
	return i, err
}
